
export const testdata = {
  "data": [
  {
  "ID": "Tiger Nixon",
  "JOBS": "System Architect",
  "salary": "$320,800",
  "start_date": "2011/04/25",
  "office": "Edinburgh",
  "extn": "5421"
  },
  {
  "ID": "Garrett Winters",
  "JOBS": "Accountant",
  "salary": "$170,750",
  "start_date": "2011/07/25",
  "office": "Tokyo",
  "extn": "8422"
  },
  {
  "name": "Ashton Cox",
  "position": "Junior Technical Author",
  "salary": "$86,000",
  "start_date": "2009/01/12",
  "office": "San Francisco",
  "extn": "1562"
  },
  {
  "name": "Cedric Kelly",
  "position": "Senior Javascript Developer",
  "salary": "$433,060",
  "start_date": "2012/03/29",
  "office": "Edinburgh",
  "extn": "6224"
  },
]}

const tableContent = [
  {
    jobId: 24122,
    partName: 'Front Schaden - Stoßstange',
    model: 'Porsche/Macan S',
    numberPlate: 'A-PO 1499',
    numberOfParts: 5,
    completion: '12/10/22',
    name: "Neu",
    title: 'Neu',
    subRows: [{
      jobId: 14122,
      partName: 'Front Schaden - Stoßstange',
      model: 'Porsche/Macan S',
      numberPlate: 'A-PO 1499',
      numberOfParts: 5,
      completion: '12/10/22',
      name: "Neu",
      title: 'Neu',
  },
  {
    jobId: 24122,
    partName: 'Front Schaden - Stoßstange',
    model: 'Porsche/ Macan S',
    numberPlate: 'A-PO 1499',
    numberOfParts: 5,
    completion: '12/10/22',
    name: "Neu",
    title: 'Neu',
},
]},
  {
    jobId: 24592,
    partName: 'Schaden an der Hinterachse',
    model: 'VW/T-Roc',
    numberPlate: 'S-EA 1334',
    numberOfParts: 4,
    completion: '15/10/22',
    name: "Bestellt",
    title: 'Bestellt',
  },
  {
    jobId: 34592,
    partName: 'Schaden an der Hinterachse',
    model: 'VW/T-Roc',
    numberPlate: 'S-EA 1334',
    numberOfParts: 4,
    completion: '15/10/22',
    name: "Geliefert",
    title: 'Geliefert',
  },
  {
    jobId: 44592,
    partName: 'Schaden an der Hinterachse',
    model: 'VW/T-Roc',
    numberPlate: 'S-EA 1334',
    numberOfParts: 4,
    completion: '15/10/22',
    name: "Reklamationen",
    title: 'Reklamationen',
  },
  {
    jobId: 54592,
    partName: 'Schaden an der Hinterachse',
    model: 'VW/T-Roc',
    numberPlate: 'S-EA 1334',
    numberOfParts: 4,
    completion: '15/10/22',
    name: "Abgeschlossen",
    title: 'Abgeschlossen',
  }
]



export const tabContent = [
  { jobId: 24122,
    name: "Neu",
    'table' : {
    jobId: 24122,
    partName: 'Front Schaden - Stoßstange',
    model: 'Porsche / Macan S',
    numberPlate: 'A-PO 1499',
    numberOfParts: 5,
    completion: '02/01/22',
    name: "Neu",
    title: 'Neu',
  },
  'table2' : {
    jobId2: 24592,
    partName2: 'Schaden an der Hinterachse',
    model2: 'VW / T-Roc',
    numberPlate2: 'S-EA 1334',
    numberOfParts2: 4,
    completion2: '22/12/22',
    name2: "Neu",
    title2: 'Neu',
  }
  },
  { jobId: 24592,
    name: "Bestellt",
    'table': {
    jobId: 24132,
    partName: 'Heckschaden',
    model: 'VW / Caddy',
    numberPlate: 'A-UF 11',
    numberOfParts: 34,
    completion: '14/01/22',
    name: "Bestellt",
    title: 'Bestellt',
  },
  'table2': {
    jobId2: 24235,
    partName2: 'Stoßfänger',
    model2: 'Renault / Clio',
    numberPlate2: 'A-WC 983',
    numberOfParts2: 1,
    completion2: '03/01/22',
    name2: "Bestellt",
    title2: 'Bestellt',
  }
  },
  { jobId: 34592,
    name: "Geliefert",
    'table': {
    jobId: 24704,
    partName: 'Seitenschaden',
    model: 'BMW / X5',
    numberPlate: 'A-XX 1673',
    numberOfParts: 14,
    completion: '2/01/22',
    name: "Geliefert",
    title: 'Geliefert',
  },
  'table2': {
    jobId2: 24352,
    partName2: 'Seitenspiegel Links',
    model2: 'Opel / Astra',
    numberPlate2: 'M-EL 4578',
    numberOfParts2: 3,
    completion2: '23/12/22',
    name2: "Geliefert",
    title2: 'Geliefert',
  }
  },
  {
    jobId: 44592,
    name: "Reklamationen",
    'table': {
    jobId: 24125,
    partName: 'Heckschaden',
    model: 'BMW / X4',
    numberPlate: 'A-U 23',
    numberOfParts: 5,
    completion: '02/01/22',
    name: "Reklamationen",
    title: 'Reklamationen',
  },
  'table2': {
    jobId2: 24123,
    partName2: 'Front Schaden - Stoßstange',
    model2: 'BMW / M1',
    numberPlate2: 'A-SU 555',
    numberOfParts2: 7,
    completion2: '02/01/22',
    name2: "Reklamationen",
    title2: 'Reklamationen',
  }
  },
  {
    jobId: 54592,
    name: "Abgeschlossen",
    'table': {
    jobId: 24144,
    partName: 'Heckscheibe',
    model: 'Skoda / Superb',
    numberPlate: 'A-PI 198',
    numberOfParts: 3,
    completion: '18/02/22',
    name: "Abgeschlossen",
    title: 'Abgeschlossen',
  },
  'table2': {
    jobId2: 24556,
    partName2: 'Unterboden Schaden',
    model2: 'VW / Golf',
    numberPlate2: 'K-FI 1389',
    numberOfParts2: 13,
    completion2: '18/02/22',
    name2: "Abgeschlossen",
    title2: 'Abgeschlossen',
  }
  }
];

export const steeringTabContent = [
  { stId: 24592,
    name: "Tool",
    'table': {
    stId: 24132,
    insuranceCont: 'Basic',
    ageOfCar: '0-3',
    workshop: 'Fix-It-All Auto',
    partDealer: 'Partdealer',
    status: 'In Bearbeitung',
    process: 'Process',
    date: "12/06/22",
  },
  'table2': {
    stId2: 24132,
    insuranceCont2: 'Advance',
    ageOfCar2: '3-6',
    workshop2: 'Auto Papa Repair Shop',
    partDealer2: 'Partdealer',
    status2: 'In Bearbeitung',
    process2: 'Process',
    date2: "12/06/22",
  },
  'table3': {
    stId3: 24132,
    insuranceCont3: 'Premium',
    ageOfCar3: '6-10',
    workshop3: 'Motor Madness',
    partDealer3: 'Partdealer',
    status3: 'In Bearbeitung',
    process3: 'Process',
    date3: "12/06/22",
  },
  'table4': {
    stId4: 24132,
    insuranceCont4: '',
    ageOfCar4: '10-14',
    workshop4: 'Fix-It-All Auto',
    partDealer4: 'Partdealer',
    status4: 'In Bearbeitung',
    process4: 'Process',
    date4: "12/06/22",
  }
  },
  { stId: 24122,
    name: "Rules",
    'table' : {
      stId4: 24132,
      insuranceCont4: '',
      ageOfCar4: '10-14',
      workshop4: 'Fix-It-All Auto',
      partDealer4: 'Partdealer',
      status4: 'In Bearbeitung',
      process4: 'Process',
      date4: "12/06/22",
  },
  'table2' : {
    stId4: 24132,
    insuranceCont4: '',
    ageOfCar4: '10-14',
    workshop4: 'Fix-It-All Auto',
    partDealer4: 'Partdealer',
    status4: 'In Bearbeitung',
    process4: 'Process',
    date4: "12/06/22",
  },
  'table3': {
    stId3: 24132,
    insuranceCont3: 'Premium',
    ageOfCar3: '6-10',
    workshop3: 'Motor Madness',
    partDealer3: 'Partdealer',
    status3: 'In Bearbeitung',
    process3: 'Process',
    date3: "12/06/22",
  },
  'table4': {
    stId4: 24132,
    insuranceCont4: '',
    ageOfCar4: '10-14',
    workshop4: 'Fix-It-All Auto',
    partDealer4: 'Partdealer',
    status4: 'In Bearbeitung',
    process4: 'Process',
    date4: "12/06/22",
  }
  },
];

export default tableContent;
